// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdi3OkcmZEutPPxkT-uJswl6H2N4H-ZFU',
    appId: '1:953141943816:web:b60be0d215f2d97f66fbbd',
    messagingSenderId: '953141943816',
    projectId: 'paktvdramas-59c5a',
    authDomain: 'paktvdramas-59c5a.firebaseapp.com',
    storageBucket: 'paktvdramas-59c5a.firebasestorage.app',
    measurementId: 'G-QR56VYMB0V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdDKyqVY2zpp2cYmst2lPlaqxZjjqc0qc',
    appId: '1:953141943816:android:4b8a75eac7484d0366fbbd',
    messagingSenderId: '953141943816',
    projectId: 'paktvdramas-59c5a',
    storageBucket: 'paktvdramas-59c5a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBplIEUpC0o26D-V4zMeQntbzpJq_AhPDI',
    appId: '1:953141943816:ios:335d6b1fa051c93566fbbd',
    messagingSenderId: '953141943816',
    projectId: 'paktvdramas-59c5a',
    storageBucket: 'paktvdramas-59c5a.firebasestorage.app',
    androidClientId: '953141943816-blohva5snfpa5nqfjca2aac6k1aptheg.apps.googleusercontent.com',
    iosClientId: '953141943816-pa79pii5nquoohc1pf5h7htenv89qorr.apps.googleusercontent.com',
    iosBundleId: 'com.media.monitors.uielem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBplIEUpC0o26D-V4zMeQntbzpJq_AhPDI',
    appId: '1:953141943816:ios:da8209ce6a2b8c9266fbbd',
    messagingSenderId: '953141943816',
    projectId: 'paktvdramas-59c5a',
    storageBucket: 'paktvdramas-59c5a.firebasestorage.app',
    androidClientId: '953141943816-blohva5snfpa5nqfjca2aac6k1aptheg.apps.googleusercontent.com',
    iosClientId: '953141943816-f2ke8khjvie7j9o4l3edcmg0ub3gicop.apps.googleusercontent.com',
    iosBundleId: 'com.example.uielem',
  );
}
